### ISSUE TITLE
Asset library submission's download link is broken

### ISSUE THREAD

**Issue by Calinou** [Wavesonics/LANServerBroadcast#1]
Hello,

The asset library submission you made points to a tag `release-1.0` which doesn't exist. Therefore, the asset can't be downloaded. Could you create a tag named `release-1.0` and push it to GitHub to fix this, please? :slightly_smiling_face:

I'll approve the asset once this is done.

**Comment by Wavesonics** [comment]
Whopsy, fixed!

@Calinou thanks for pointing that out.

**Comment by Calinou** [comment]
I approved the asset: https://godotengine.org/asset-library/asset/443

**Comment by Wavesonics** [comment]
@Calinou awesome, thanks!
