### ISSUE TITLE
LANServerBroadcast not working.

### ISSUE THREAD

**Issue by superRaptor911** [Wavesonics/LANServerBroadcast#2]
Unable to get hosted server.
Its working If i change
`socketUDP.set_dest_address("255.255.255.255", broadcastPort)`
to
`socketUDP.set_dest_address("0.0.0.0", broadcastPort)`

im using Godot 3.2 and os is ubuntu 18.04

**Comment by Wavesonics** [comment]
Ah yup, I believe that was added in 3.2, thanks for the PR
