### ISSUE TITLE
Broadcasting non ascii characters

### ISSUE THREAD

**Issue by spyr0s** [Wavesonics/LANServerBroadcast#6]
I had a problem broadcasting non ascii characters (Greek names)
I fixed it by changing 
in ServerAdvertiser.gd line 30
`var packet := packetMessage.to_ascii()`
to
`var packet := packetMessage.to_utf8()`

and in ServerListener line 40
`var serverMessage = array_bytes.get_string_from_ascii()`
to
`var serverMessage = array_bytes.get_string_from_utf8()`

According to Godot Docs

```
String get_string_from_utf8()

Returns a copy of the array's contents as String. Slower than get_string_from_ascii() but supports 
UTF-8 encoded data.
Use this function if you are unsure about the source of the data.
For user input this function should always be preferred.

**Comment by Wavesonics** [comment]
Ya that looks correct, would you mind opening a pull request?
